<?php

namespace Container82WMUb2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mt0ng2fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mt0ng2f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mt0ng2f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'repository' => ['privates', 'App\\Repository\\BooksRepository', 'getBooksRepositoryService', true],
        ], [
            'managerRegistry' => '?',
            'repository' => 'App\\Repository\\BooksRepository',
        ]);
    }
}
