<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container82WMUb2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container82WMUb2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container82WMUb2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container82WMUb2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container82WMUb2\App_KernelDevDebugContainer([
    'container.build_hash' => '82WMUb2',
    'container.build_id' => '51ca4738',
    'container.build_time' => 1697489721,
], __DIR__.\DIRECTORY_SEPARATOR.'Container82WMUb2');
